# Verwende das offizielle Node-RED-Image
FROM nodered/node-red

# Setze den Port, auf dem Node-RED läuft
ENV PORT=8080

# Exponiere den Port
EXPOSE 8080

# Startbefehl für Node-RED
CMD ["npm", "start", "--", "-p", "8080"]
